SELECT DISTINCT HOUFT.NAME
              ,  HOIF.ORG_INFORMATION2 "Value Set Id"
              ,  HOIF.ORG_INFORMATION3 "Cost Center 1"
              ,  HOIF.ORG_INFORMATION7 "Record Identifier"
FROM HR_ORGANIZATION_INFORMATION_F HOIF
   ,  HR_ORGANIZATION_UNITS_F_TL HOUFT
WHERE TRUNC(SYSDATE) BETWEEN HOIF.EFFECTIVE_START_DATE AND HOIF.EFFECTIVE_END_DATE
  AND HOUFT.ORGANIZATION_ID = HOIF.ORGANIZATION_ID
  AND HOIF.ORG_INFORMATION_CONTEXT = 'PER_GL_COST_CENTER_INFO'
  AND HOUFT.LANGUAGE = 'US'
  AND TRUNC(SYSDATE) BETWEEN HOUFT.EFFECTIVE_START_DATE AND HOUFT.EFFECTIVE_END_DATE
  AND 300000040564074
ORDER BY 1