-- 83.950 PER_PERIODS_OF_SERVICE
-- 58.507 (+)

WITH Duplicate AS (
SELECT 
PeriodsOfService.PERSON_ID,
COUNT(1) RECORDS
/*
AllPeople.PERSON_NUMBER,
AllAssignments.ASSIGNMENT_NUMBER,
PersonNames.FULL_NAME,
PeriodsOfService.DATE_START,
AllAssignments.ASSIGNMENT_TYPE,
AllAssignments.EMPLOYEE_CATEGORY,
AllAssignments.ASSIGNMENT_STATUS_TYPE,
CollectiveAgreement.INTERNAL_ADDRESS_LINE COLLECTIVE_CODE,
CollectiveAgreement.NAME COLLECTIVE_NAME */
FROM PER_PERIODS_OF_SERVICE PeriodsOfService
LEFT JOIN PER_ALL_ASSIGNMENTS_M AllAssignments ON AllAssignments.ASSIGNMENT_TYPE='E'
AND AllAssignments.PERSON_ID = PeriodsOfService.PERSON_ID
AND AllAssignments.PERIOD_OF_SERVICE_ID = PeriodsOfService.PERIOD_OF_SERVICE_ID
AND NVL(PeriodsOfService.ACTUAL_TERMINATION_DATE, '4712-12-31') BETWEEN AllAssignments.EFFECTIVE_START_DATE AND AllAssignments.EFFECTIVE_END_DATE
--LEFT JOIN PER_ALL_PEOPLE_F AllPeople ON AllPeople.PERSON_ID = PeriodsOfService.PERSON_ID
--AND AllAssignments.EFFECTIVE_END_DATE BETWEEN AllPeople.EFFECTIVE_START_DATE AND AllPeople.EFFECTIVE_END_DATE
--LEFT JOIN PER_PERSON_NAMES_F PersonNames ON PersonNames.PERSON_ID = AllPeople.PERSON_ID
--AND PersonNames.NAME_TYPE = 'GLOBAL'
--LEFT JOIN HR_ORGANIZATION_V CollectiveAgreement ON (CollectiveAgreement.ORGANIZATION_ID = AllAssignments.UNION_ID AND CollectiveAgreement.STATUS = 'A' AND CollectiveAgreement.CLASSIFICATION_CODE = 'ORA_PER_UNION' AND AllAssignments.EFFECTIVE_END_DATE BETWEEN CollectiveAgreement.EFFECTIVE_START_DATE AND CollectiveAgreement.EFFECTIVE_END_DATE)
--LEFT JOIN HR_ORGANIZATION_V Department ON (Department.ORGANIZATION_ID = AllAssignments.ORGANIZATION_ID AND Department.CLASSIFICATION_CODE = 'DEPARTMENT' AND AllAssignments.EFFECTIVE_END_DATE BETWEEN Department.EFFECTIVE_START_DATE AND Department.EFFECTIVE_END_DATE)
--WHERE (PeriodsOfService.ACTUAL_TERMINATION_DATE IS NULL OR SYSDATE < PeriodsOfService.ACTUAL_TERMINATION_DATE)
WHERE AllAssignments.PERSON_ID
GROUP BY PeriodsOfService.PERSON_ID )
SELECT * FROM Duplicate WHERE RECORDS > 1
  --AND AllPeople.PERSON_NUMBER = '1000321'

-- SELECT * FROM PER_ALL_PEOPLE_F WHERE PERSON_NUMBER = '1000321'
-- SELECT * FROM PER_ALL_ASSIGNMENTS_M WHERE ASSIGNMENT_TYPE='E' AND
-- SELECT * FROM PER_PERSONS
-- SELECT * FROM PER_PERSON_NAMES_F
-- SELECT * FROM HR_ORGANIZATION_V
