SELECT *
FROM
  (SELECT PU.PERSON_ID
        , PU.USERNAME
        , PPNF.FULL_NAME
        , PU.SUSPENDED
        , PU.HR_TERMINATED
        , PU.ACTIVE_FLAG
        , PRDT.ROLE_ID
        , PRDT.ROLE_NAME
        , PRD.ROLE_COMMON_NAME
        , PU.CREATION_DATE
        , PU.CREATED_BY
        , PU.LAST_UPDATE_DATE
        , PU.LAST_UPDATED_BY
        , PU.CREDENTIALS_EMAIL_SENT
   FROM PER_USER_ROLES PUR
   INNER JOIN PER_USERS PU ON PU.USER_ID = PUR.USER_ID
   AND PU.ACTIVE_FLAG = UPPER('Y')
   INNER JOIN PER_ROLES_DN_TL PRDT ON PRDT.ROLE_ID = PUR.ROLE_ID
   AND PRDT.LANGUAGE = USERENV('lang')
   INNER JOIN PER_ROLES_DN PRD ON PRD.ROLE_ID = PRDT.ROLE_ID
   INNER JOIN PER_PERSON_NAMES_F PPNF ON PPNF.PERSON_ID = PU.PERSON_ID
   AND PPNF.NAME_TYPE = 'GLOBAL'
   AND TRUNC(SYSDATE) BETWEEN PPNF.EFFECTIVE_START_DATE AND PPNF.EFFECTIVE_END_DATE
   WHERE 1 = 1
     AND PU.USERNAME LIKE 'GM%'
     AND NVL(PU.SUSPENDED, UPPER('N')) = UPPER('N'))