SELECT
    PER_NI.NATIONAL_IDENTIFIER_NUMBER AS CPF,
    PER_PF.PERSON_NUMBER AS NUMERO_DA_PESSOA,
    PER_ASN.ASSIGNMENT_NUMBER AS NUMERO_ATRIBUICAO,
    SUBSTR(PER_ASN.ASSIGNMENT_NUMBER, 1, 3) AS CODIGO_EMPRESA_ATRIBUICAO,
    SUBSTR(PER_ASN.ASSIGNMENT_NUMBER, 4) AS MATRICULA_ATRIBUICAO,
    PER_PN.FULL_NAME AS NOME_COLABORADOR,
    ORG_LEMP.NAME AS NOME_EMPRESA_LEGAL,
    ORG_BU.NAME AS NOME_UNIDADE_NEGOCIO,
    ACT_TL.ACTION_NAME AS NOME_ACAO,
    REA_TL.ACTION_REASON AS MOTIVO_ACAO,
    STA_TL.USER_STATUS AS STATUS_ATRIBUICAO,
    PER_TP.SYSTEM_PERSON_TYPE AS TIPO_PESSOA_SISTEMA,
    PER_PL.USER_PERSON_TYPE AS TIPO_PESSOA_USUARIO,
    NVL(SEN_DT.ENTRY_DATE, PER_ASN.EFFECTIVE_START_DATE) AS DATA_ADMISSAO,
    TO_CHAR(PER_ASN.EFFECTIVE_START_DATE, 'DD/MM/YYYY') AS DATA_MOVIMENTACAO,
    TO_CHAR(PER_ASN.EFFECTIVE_END_DATE, 'DD/MM/YYYY') AS DATA_FINAL_ATRIBUICAO,
    ORG_RIF.ORG_INFORMATION1 AS CODIGO_FILIAL_INFO,
    ORG_EST.NAME AS NOME_FILIAL,
    TO_CHAR(PER_POS.ACTUAL_TERMINATION_DATE, 'DD/MM/YYYY') AS DATA_DESLIGAMENTO,
    LKP_TERM.MEANING AS MOTIVO_REMOCAO_DESLIGAMENTO,
    ORG_DEPT.INTERNAL_ADDRESS_LINE AS CODIGO_DEPARTAMENTO,
    ORG_DEPT.NAME AS NOME_DEPARTAMENTO,
    JOB_B.JOB_CODE AS CODIGO_CARGO,
    JOB_TL.NAME AS NOME_CARGO,
    ORG_SDC.INTERNAL_ADDRESS_LINE AS CODIGO_SINDICATO,
    ORG_SDC.NAME AS NOME_SINDICATO,
    SAL.SALARY_AMOUNT AS VALOR_SALARIO,
    POS_B.POSITION_CODE AS CODIGO_POSICAO,
    POS_TL.NAME AS NOME_POSICAO,
    DIS.DISABILITY_ID AS CODIGO_DEFICIENCIA,
    TO_CHAR(PER_ASN.CREATION_DATE, 'DD/MM/YYYY HH24:MI:SS') AS DATA_CRIACAO_ATRIBUICAO
FROM
    PER_ALL_ASSIGNMENTS_M PER_ASN
LEFT JOIN PER_PERIODS_OF_SERVICE PER_POS ON PER_POS.PERIOD_OF_SERVICE_ID = PER_ASN.PERIOD_OF_SERVICE_ID
LEFT JOIN PER_PERIODS_OF_SERVICE PER_PT ON PER_PT.PERIOD_OF_SERVICE_ID = PER_ASN.PERIOD_OF_SERVICE_ID
    AND PER_PT.ATTRIBUTE_CATEGORY = 'LACLS_BR_HCM_INFO_TERM'
LEFT JOIN FND_LOOKUP_VALUES_TL LKP_TERM ON LKP_TERM.LOOKUP_CODE = PER_PT.ATTRIBUTE2
    AND LKP_TERM.LOOKUP_TYPE = 'LACLS_BR_HCM_REA_PAY_TERM'
    AND LKP_TERM.LANGUAGE = USERENV('LANG')
LEFT JOIN PER_PERIODS_OF_SERVICE PER_PA ON PER_PA.PERIOD_OF_SERVICE_ID = PER_ASN.PERIOD_OF_SERVICE_ID
    AND PER_PA.ATTRIBUTE_CATEGORY = 'LACLS_BR_HCM_WORK_REL'
LEFT JOIN PER_PERSON_NAMES_F PER_PN ON PER_PN.PERSON_ID = PER_ASN.PERSON_ID
    AND PER_PN.NAME_TYPE = 'BR'
    AND TRUNC(SYSDATE) BETWEEN PER_PN.EFFECTIVE_START_DATE AND PER_PN.EFFECTIVE_END_DATE
LEFT JOIN PER_ALL_PEOPLE_F PER_PF ON PER_PF.PERSON_ID = PER_ASN.PERSON_ID
    AND TRUNC(SYSDATE) BETWEEN PER_PF.EFFECTIVE_START_DATE AND PER_PF.EFFECTIVE_END_DATE
LEFT JOIN PER_PERSON_TYPE_USAGES_M PER_TP ON PER_TP.PERSON_ID = PER_ASN.PERSON_ID
    AND PER_TP.SYSTEM_PERSON_TYPE IN ('CWK', 'EMP', 'NONW')
    AND TRUNC(SYSDATE) BETWEEN PER_TP.EFFECTIVE_START_DATE AND PER_TP.EFFECTIVE_END_DATE
LEFT JOIN PER_PERSON_TYPES_TL PER_PL ON PER_PL.PERSON_TYPE_ID = PER_TP.PERSON_TYPE_ID
    AND PER_PL.LANGUAGE = USERENV('LANG')
LEFT JOIN PER_ASSIGNMENT_STATUS_TYPES_TL STA_TL ON STA_TL.ASSIGNMENT_STATUS_TYPE_ID = PER_ASN.ASSIGNMENT_STATUS_TYPE_ID
    AND STA_TL.LANGUAGE = USERENV('LANG')
LEFT JOIN PER_NATIONAL_IDENTIFIERS PER_NI ON PER_NI.PERSON_ID = PER_PF.PERSON_ID
    AND PER_NI.NATIONAL_IDENTIFIER_TYPE = 'CPF'
LEFT JOIN HR_ORGANIZATION_V ORG_DEPT ON ORG_DEPT.ORGANIZATION_ID = PER_ASN.ORGANIZATION_ID
    AND ORG_DEPT.CLASSIFICATION_CODE = 'DEPARTMENT'
    AND ORG_DEPT.STATUS = 'A'
    AND TRUNC(SYSDATE) BETWEEN ORG_DEPT.EFFECTIVE_START_DATE AND ORG_DEPT.EFFECTIVE_END_DATE
LEFT JOIN HR_ORGANIZATION_V ORG_LEMP ON ORG_LEMP.ORGANIZATION_ID = PER_ASN.LEGAL_ENTITY_ID
    AND ORG_LEMP.CLASSIFICATION_CODE = 'HCM_LEMP'
    AND ORG_LEMP.STATUS = 'A'
    AND TRUNC(SYSDATE) BETWEEN ORG_LEMP.EFFECTIVE_START_DATE AND ORG_LEMP.EFFECTIVE_END_DATE
LEFT JOIN HR_ORGANIZATION_V ORG_BU ON ORG_BU.ORGANIZATION_ID = PER_ASN.BUSINESS_UNIT_ID
    AND ORG_BU.CLASSIFICATION_CODE = 'FUN_BUSINESS_UNIT'
    AND ORG_BU.STATUS = 'A'
    AND TRUNC(SYSDATE) BETWEEN ORG_BU.EFFECTIVE_START_DATE AND ORG_BU.EFFECTIVE_END_DATE
LEFT JOIN HR_ORGANIZATION_V ORG_SDC ON ORG_SDC.ORGANIZATION_ID = PER_ASN.UNION_ID
    AND ORG_SDC.CLASSIFICATION_CODE = 'ORA_PER_UNION'
    AND ORG_SDC.STATUS = 'A'
    AND TRUNC(SYSDATE) BETWEEN ORG_SDC.EFFECTIVE_START_DATE AND ORG_SDC.EFFECTIVE_END_DATE
LEFT JOIN PER_JOBS_F JOB_B ON JOB_B.JOB_ID = PER_ASN.JOB_ID
    AND TRUNC(SYSDATE) BETWEEN JOB_B.EFFECTIVE_START_DATE AND JOB_B.EFFECTIVE_END_DATE
LEFT JOIN PER_JOBS_F_TL JOB_TL ON JOB_TL.JOB_ID = JOB_B.JOB_ID
    AND JOB_TL.LANGUAGE = USERENV('LANG')
    AND TRUNC(SYSDATE) BETWEEN JOB_TL.EFFECTIVE_START_DATE AND JOB_TL.EFFECTIVE_END_DATE
LEFT JOIN PER_ACTION_OCCURRENCES ACT_OCC ON ACT_OCC.ACTION_OCCURRENCE_ID = PER_ASN.ACTION_OCCURRENCE_ID
LEFT JOIN PER_ACTIONS_B ACT_B ON ACT_B.ACTION_ID = ACT_OCC.ACTION_ID
LEFT JOIN PER_ACTIONS_TL ACT_TL ON ACT_TL.ACTION_ID = ACT_B.ACTION_ID
    AND ACT_TL.LANGUAGE = USERENV('LANG')
LEFT JOIN PER_ACTION_REASONS_B REA_B ON REA_B.ACTION_REASON_ID = ACT_OCC.ACTION_REASON_ID
LEFT JOIN PER_ACTION_REASONS_TL REA_TL ON REA_TL.ACTION_REASON_ID = REA_B.ACTION_REASON_ID
    AND REA_TL.LANGUAGE = USERENV('LANG')
LEFT JOIN FND_LOOKUP_VALUES_TL LKP_FRE ON LKP_FRE.LOOKUP_CODE = PER_ASN.FREQUENCY
    AND LKP_FRE.LOOKUP_TYPE = 'FREQUENCY'
    AND LKP_FRE.LANGUAGE = USERENV('LANG')
LEFT JOIN FND_LOOKUP_VALUES_TL LKP_UNI ON LKP_UNI.LOOKUP_CODE = PER_ASN.PROBATION_UNIT
    AND LKP_UNI.LOOKUP_TYPE = 'QUALIFYING_UNITS'
    AND LKP_UNI.LANGUAGE = USERENV('LANG')
LEFT JOIN FND_LOOKUP_VALUES_TL LKP_UNII ON LKP_UNII.LOOKUP_CODE = PER_ASN.NOTICE_PERIOD_UOM
    AND LKP_UNII.LOOKUP_TYPE = 'QUALIFYING_UNITS'
    AND LKP_UNII.LANGUAGE = USERENV('LANG')
LEFT JOIN FND_LOOKUP_VALUES_TL LKP_EP_CTG ON LKP_EP_CTG.LOOKUP_CODE = PER_ASN.ASS_ATTRIBUTE2
    AND LKP_EP_CTG.LOOKUP_TYPE = 'ORA_HRX_BR_WORKER_CATEGORY'
    AND LKP_EP_CTG.LANGUAGE = USERENV('LANG')
LEFT JOIN FND_LOOKUP_VALUES_TL LKP_CO_CTG ON LKP_CO_CTG.LOOKUP_CODE = PER_ASN.EMPLOYEE_CATEGORY
    AND LKP_CO_CTG.LOOKUP_TYPE = 'EMPLOYEE_CATG'
    AND LKP_CO_CTG.LANGUAGE = USERENV('LANG')
LEFT JOIN FND_LOOKUP_VALUES_TL LKP_FPT ON LKP_FPT.LOOKUP_CODE = PER_ASN.FULL_PART_TIME
    AND LKP_FPT.LOOKUP_TYPE = 'PART_FULL_TIME'
    AND LKP_FPT.LANGUAGE = USERENV('LANG')
LEFT JOIN FND_LOOKUP_VALUES_TL LKP_HS ON LKP_HS.LOOKUP_CODE = PER_ASN.HOURLY_SALARIED_CODE
    AND LKP_HS.LOOKUP_TYPE = 'HOURLY_SALARIED_CODE'
    AND LKP_HS.LANGUAGE = USERENV('LANG')
LEFT JOIN FND_LOOKUP_VALUES_TL LKP_RT ON LKP_RT.LOOKUP_CODE = PER_ASN.PERMANENT_TEMPORARY_FLAG
    AND LKP_RT.LOOKUP_TYPE = 'REGULAR_TEMPORARY'
    AND LKP_RT.LANGUAGE = USERENV('LANG')
LEFT JOIN HR_ALL_POSITIONS_F POS_B ON POS_B.POSITION_ID = PER_ASN.POSITION_ID
    AND TRUNC(SYSDATE) BETWEEN POS_B.EFFECTIVE_START_DATE AND POS_B.EFFECTIVE_END_DATE
LEFT JOIN HR_ALL_POSITIONS_F_TL POS_TL ON POS_TL.POSITION_ID = POS_B.POSITION_ID
    AND POS_TL.LANGUAGE = USERENV('LANG')
    AND TRUNC(SYSDATE) BETWEEN POS_TL.EFFECTIVE_START_DATE AND POS_TL.EFFECTIVE_END_DATE
LEFT JOIN PER_DISABILITIES_F DIS ON DIS.PERSON_ID = PER_PF.PERSON_ID
    AND TRUNC(SYSDATE) BETWEEN DIS.EFFECTIVE_START_DATE AND DIS.EFFECTIVE_END_DATE
LEFT JOIN CMP_SALARY SAL ON SAL.ASSIGNMENT_ID = PER_ASN.ASSIGNMENT_ID
    AND TRUNC(SYSDATE) BETWEEN SAL.DATE_FROM AND SAL.DATE_TO
LEFT JOIN PER_SENIORITY_DATES_F SEN_DT ON SEN_DT.PERSON_ID = PER_PF.PERSON_ID
    AND SEN_DT.LEVEL_CODE = 'ORA_P'
    AND SEN_DT.SENIORITY_DATE_CODE IN ('LACLS_BR_HCM_SD_E', 'ORA_PER_MIGR_ESD_P')
    AND TRUNC(SYSDATE) BETWEEN SEN_DT.EFFECTIVE_START_DATE AND SEN_DT.EFFECTIVE_END_DATE
    AND SEN_DT.ENTRY_DATE = (SELECT MAX(SEN_DTX.ENTRY_DATE)
                           FROM PER_SENIORITY_DATES_F SEN_DTX
                           WHERE SEN_DTX.PERSON_ID = PER_PF.PERSON_ID
                             AND SEN_DTX.LEVEL_CODE = 'ORA_P'
                             AND TRUNC(SYSDATE) BETWEEN SEN_DTX.EFFECTIVE_START_DATE AND SEN_DTX.EFFECTIVE_END_DATE
                           GROUP BY SEN_DTX.PERSON_ID)
LEFT JOIN XLE_REGISTRATIONS_V XLE_REG ON XLE_REG.REGISTRATION_NUMBER = PER_ASN.ASS_ATTRIBUTE19
    AND XLE_REG.LEGAL_ENTITY_ID IS NULL
    AND TRUNC(SYSDATE) BETWEEN NVL(XLE_REG.EFFECTIVE_FROM, TO_DATE('1951-01-01', 'yyyy-mm-dd')) AND NVL(XLE_REG.EFFECTIVE_TO, TO_DATE('4712-12-31', 'yyyy-mm-dd'))
LEFT JOIN HR_ORGANIZATION_V ORG_EST ON ORG_EST.ESTABLISHMENT_ID = XLE_REG.ESTABLISHMENT_ID
    AND ORG_EST.STATUS = 'A'
    AND ORG_EST.CLASSIFICATION_CODE = 'HCM_REPORTING_ESTABLISHMENT'
    AND TRUNC(SYSDATE) BETWEEN ORG_EST.EFFECTIVE_START_DATE AND ORG_EST.EFFECTIVE_END_DATE
LEFT JOIN HR_ORGANIZATION_INFORMATION_F ORG_RIF ON ORG_RIF.ORG_INFORMATION_CONTEXT = 'LACLS_BR_HCM_LRU_CODE'
    AND ORG_RIF.ORGANIZATION_ID = ORG_EST.ORGANIZATION_ID
    AND TRUNC(SYSDATE) BETWEEN ORG_RIF.EFFECTIVE_START_DATE AND ORG_RIF.EFFECTIVE_END_DATE
WHERE
    PER_ASN.ASSIGNMENT_TYPE IN ('E') -- 'E' para Empregado
    AND STA_TL.ASSIGNMENT_STATUS_TYPE_ID = 1 -- Ativo e Elegível para a Folha de Pagamento - Active - Payroll Eligible
    AND TRUNC(SYSDATE) BETWEEN PER_ASN.EFFECTIVE_START_DATE AND PER_ASN.EFFECTIVE_END_DATE
ORDER BY
    PER_ASN.EFFECTIVE_START_DATE,
    PER_ASN.EFFECTIVE_SEQUENCE,
    TO_NUMBER(PER_PF.PERSON_NUMBER),
    PER_POS.DATE_START;