SELECT *
FROM
  (SELECT ALLASSIGNMENT.PERSON_ID AS PERSON_ID
        , ALLPEOPLE.PERSON_NUMBER AS PERSON_NUMBER
        , SUBSTR (ALLASSIGNMENT.ASSIGNMENT_NUMBER, 1, 3) AS EMPLOYER
        , SUBSTR (ALLASSIGNMENT.ASSIGNMENT_NUMBER, 4, LENGTH (ALLASSIGNMENT.ASSIGNMENT_NUMBER)) AS EMPLOYEE
        , ALLASSIGNMENT.ASSIGNMENT_NUMBER AS ASSIGNMENT_NUMBER
        , REGEXP_REPLACE (CPF.NATIONAL_IDENTIFIER_NUMBER, '\W') AS NATIONAL_IDENTIFIER_NUMBER
        , PERSONNAMES.FULL_NAME AS FULL_NAME
        , ABSENCERECORDS.PERIOD_OF_SERVICE_ID AS PERIOD_OF_SERVICE_ID
        , TO_DATE (ABSENCERECORDS.START_DATE, 'YYYY-MM-DD') AS START_DATE
        , ABSENCERECORDS.START_TIME AS START_TIME
        , ABSENCERECORDS.PER_ABSENCE_ENTRY_ID AS PER_ABSENCE_ENTRY_ID
        , ABSENCERECORDS.LEGAL_ENTITY_ID AS LEGAL_ENTITY_ID
        , ABSENCERECORDS.ABSENCE_TYPE_ID AS ABSENCE_TYPE_ID
        , ABSENCETYPES.NAME AS NAME
        , COALESCE(ABSENCERECORDS.END_DATE, TO_DATE('4712-12-31', 'YYYY-MM-DD')) AS END_DATE
        , COALESCE(ABSENCERECORDS.END_TIME, '23:59') AS END_TIME
        , ABSENCERECORDS.DURATION AS DURATION
        , ABSENCERECORDS.SINGLE_DAY_FLAG AS SINGLE_DAY_FLAG
        , ABSENCERECORDS.START_DATE_DURATION AS START_DATE_DURATION
        , ABSENCERECORDS.END_DATE_DURATION AS END_DATE_DURATION
        , ABSENCETYPES.ATTRIBUTE1 AS ABSENCETYPES_ATTR1
        , ABSENCETYPES.ATTRIBUTE2 AS ABSENCETYPES_ATTR2
        , ABSENCETYPES.ATTRIBUTE3 AS ABSENCETYPES_ATTR3
        , ABSENCERECORDS.ABSENCE_ENTRY_BASIC_FLAG AS ABSENCE_ENTRY_BASIC_FLAG
        , ABSENCERECORDS.ABSENCE_STATUS_CD AS ABSENCE_STATUS_CD
        , ABSENCERECORDS.APPROVAL_STATUS_CD AS APPROVAL_STATUS_CD
        , ABSENCERECORDS.APPROVAL_DATETIME AS APPROVAL_DATETIME
        , ABSENCERECORDS.CREATED_BY AS CREATED_BY
        , ABSENCERECORDS.CREATION_DATE AS CREATION_DATE
        , ABSENCERECORDS.LAST_UPDATED_BY AS LAST_UPDATED_BY
        , ABSENCERECORDS.LAST_UPDATE_DATE AS LAST_UPDATE_DATE
        , ABSENCERECORDS.ATTRIBUTE1 AS ABSENCERECORDS_ATTR1
        , ABSENCERECORDS.ATTRIBUTE2 AS ABSENCERECORDS_ATTR2
        , ABSENCERECORDS.USER_MODE AS USER_MODE
        , ABSENCERECORDS.SOURCE AS SOURCE
        , ABSENCERECORDS.LEGISLATION_CODE AS LEGISLATION_CODE
        , ABSENCERECORDS.OVERRIDDEN AS OVERRIDDEN
        , ABSENCERECORDS.ASSIGNMENT_ID AS ASSIGNMENT_ID
        , ABSENCERECORDS.ATTRIBUTE18 AS ABSENCE_CID
        , ABSENCETYPE.BASE_NAME AS BASE_NAME
        , ABSENCETYPE.STATUS AS STATUS
        , ABSENCETYPE.MIN_DURATION AS MIN_DURATION
        , ABSENCETYPE.MAX_DURATION_RULE_CD AS MAX_DURATION_RULE_CD
        , ABSENCETYPE.MAX_DURATION AS MAX_DURATION
        , ABSENCETYPE.AGREEMENT_FLAG AS AGREEMENT_FLAG
        , ABSENCERECORDS.ABS_RECORD_SOURCE AS ABS_RECORD_SOURCE
        , SOURCE_MAP.OBJECT_NAME AS SOURCE_OBJECT_NAME
        , SOURCE_MAP.SOURCE_SYSTEM_ID
   FROM PER_ALL_ASSIGNMENTS_M ALLASSIGNMENT
   INNER JOIN PER_ALL_PEOPLE_F ALLPEOPLE ON ALLPEOPLE.PERSON_ID = ALLASSIGNMENT.PERSON_ID
   AND TRUNC (SYSDATE) BETWEEN ALLPEOPLE.EFFECTIVE_START_DATE AND ALLPEOPLE.EFFECTIVE_END_DATE
   INNER JOIN PER_PERSON_NAMES_F PERSONNAMES ON PERSONNAMES.PERSON_ID = ALLASSIGNMENT.PERSON_ID
   AND PERSONNAMES.NAME_TYPE = UPPER('GLOBAL')
   AND TRUNC (SYSDATE) BETWEEN PERSONNAMES.EFFECTIVE_START_DATE AND PERSONNAMES.EFFECTIVE_END_DATE
   INNER JOIN ANC_PER_ABS_ENTRIES ABSENCERECORDS ON ABSENCERECORDS.ASSIGNMENT_ID = ALLASSIGNMENT.ASSIGNMENT_ID
   AND ABSENCERECORDS.ABSENCE_STATUS_CD = 'SUBMITTED'
   INNER JOIN ANC_ABSENCE_TYPES_F ABSENCETYPE ON ABSENCETYPE.ABSENCE_TYPE_ID = ABSENCERECORDS.ABSENCE_TYPE_ID
   AND SYSDATE BETWEEN ABSENCETYPE.EFFECTIVE_START_DATE AND ABSENCETYPE.EFFECTIVE_END_DATE
   INNER JOIN ANC_ABSENCE_TYPES_VL ABSENCETYPES ON ABSENCETYPES.ABSENCE_TYPE_ID = ABSENCERECORDS.ABSENCE_TYPE_ID
   AND ABSENCETYPES.STATUS = UPPER('A')
   AND TRUNC (SYSDATE) BETWEEN ABSENCETYPES.EFFECTIVE_START_DATE AND ABSENCETYPES.EFFECTIVE_END_DATE
   LEFT JOIN PER_NATIONAL_IDENTIFIERS CPF ON CPF.PERSON_ID = ALLASSIGNMENT.PERSON_ID
   AND CPF.NATIONAL_IDENTIFIER_TYPE = UPPER('CPF')
   LEFT JOIN HRC_INTEGRATION_KEY_MAP SOURCE_MAP ON SOURCE_MAP.SURROGATE_ID = ABSENCERECORDS.PER_ABSENCE_ENTRY_ID
   WHERE ALLASSIGNMENT.ASSIGNMENT_TYPE = UPPER('E')
     AND ALLASSIGNMENT.ASSIGNMENT_STATUS_TYPE = UPPER('ACTIVE')
     AND ALLASSIGNMENT.EFFECTIVE_LATEST_CHANGE = UPPER('Y')
     AND TRUNC (SYSDATE) BETWEEN ALLASSIGNMENT.EFFECTIVE_START_DATE AND ALLASSIGNMENT.EFFECTIVE_END_DATE
     AND ABSENCERECORDS.START_DATE BETWEEN NVL('2025-01-01', SYSDATE) AND NVL('2025-12-31', SYSDATE))