SELECT
paf.*
FROM PER_ALL_PEOPLE_F paf
INNER JOIN  PER_PERSON_NAMES_F ppn
    ON ppn.PERSON_ID = paf.PERSON_ID
    AND ppn.NAME_TYPE='BR'
WHERE TRUNC(SYSDATE) BETWEEN ppn.EFFECTIVE_START_DATE AND ppn.EFFECTIVE_END_DATE
AND paf.PERSON_ID = '300000010288455'


/*
SELECT * FROM PER_PERSON_NAMES_F
WHERE TRUNC(SYSDATE) BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE AND NAME_TYPE='BR' AND FULL_NAME LIKE '%FRANCKLYN%'
ORDER BY EFFECTIVE_START_DATE

-- 300000010288455
*/