SELECT ABSENCETYPES.ABSENCE_TYPE_ID
     ,  ABSENCETYPES.NAME
     ,  ABSENCETYPES.DESCRIPTION
     ,  ABSENCETYPES.ATTRIBUTE1
     ,  ABSENCETYPES.ATTRIBUTE2
     ,  ABSENCETYPES.ATTRIBUTE3
     ,  ABSENCETYPES.BASE_NAME
FROM ANC_ABSENCE_TYPES_F ABSENCETYPE
INNER JOIN ANC_ABSENCE_TYPES_VL ABSENCETYPES ON ABSENCETYPES .ABSENCE_TYPE_ID = ABSENCETYPE .ABSENCE_TYPE_ID
AND ABSENCETYPES .STATUS = 'A'
WHERE 1 = 1
  AND SYSDATE BETWEEN ABSENCETYPE.EFFECTIVE_START_DATE AND ABSENCETYPE .EFFECTIVE_END_DATE --AND absencetypes .name LIKE 'Faltas%'

  AND ABSENCETYPES.ABSENCE_TYPE_ID IN (300000241996393
                                     , 300000241996319)