SELECT PAPF.PERSON_NUMBER
     , PAAM.ASSIGNMENT_NUMBER
     , PPOS.DATE_START
     , PPNF.FIRST_NAME
     , PPNF.MIDDLE_NAMES
     , PPNF.LAST_NAME
     , PPNF.FULL_NAME
     , PPNF.TITLE
     , PJFT.NAME JOB_NAME
     , HAUFT.NAME DEPARTMENT_NAME
     , HAOUF.ATTRIBUTE1
     , HAOUF.ATTRIBUTE2
     , HAOUF.ATTRIBUTE3
     , HAOUF.ATTRIBUTE4
     , TO_CHAR(PPOS.DATE_START, 'DD-MM-RRRR', 'nls_date_language=American') DATE_OF_JOINING
     , TO_CHAR(PP.DATE_OF_BIRTH, 'DD-MM-RRRR', 'nls_date_language=American') DATE_OF_BIRTH
FROM PER_ALL_PEOPLE_F PAPF
   , PER_PERSON_NAMES_F PPNF
   , PER_ALL_ASSIGNMENTS_M PAAM
   , PER_JOBS_F_TL PJFT
   , PER_PERIODS_OF_SERVICE PPOS
   , PER_PERSONS PP
   , HR_ALL_ORGANIZATION_UNITS_F HAOUF
   , HR_ORGANIZATION_UNITS_F_TL HAUFT
WHERE PAAM.PERSON_ID = PPNF.PERSON_ID
  AND PAPF.PERSON_ID = PPNF.PERSON_ID
  AND PAPF.PERSON_ID = PAAM.PERSON_ID
  AND PAAM.JOB_ID = PJFT.JOB_ID (+)
  AND PJFT.LANGUAGE = USERENV('LANG')
  AND HAUFT.LANGUAGE = USERENV('LANG')
  AND PAAM.PERIOD_OF_SERVICE_ID = PPOS.PERIOD_OF_SERVICE_ID
  AND PAAM.PERSON_ID = PP.PERSON_ID
  AND HAOUF.ORGANIZATION_ID = PAAM.ORGANIZATION_ID
  AND HAOUF.ORGANIZATION_ID = HAUFT.ORGANIZATION_ID
  AND TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
  AND TRUNC(SYSDATE) BETWEEN PAAM.EFFECTIVE_START_DATE AND PAAM.EFFECTIVE_END_DATE
  AND TRUNC(SYSDATE) BETWEEN PPNF.EFFECTIVE_START_DATE AND PPNF.EFFECTIVE_END_DATE
  AND TRUNC(SYSDATE) BETWEEN HAOUF.EFFECTIVE_START_DATE AND HAOUF.EFFECTIVE_END_DATE
  AND TRUNC(SYSDATE) BETWEEN HAUFT.EFFECTIVE_START_DATE AND HAUFT.EFFECTIVE_END_DATE
  AND TRUNC(SYSDATE) BETWEEN PJFT.EFFECTIVE_START_DATE AND PJFT.EFFECTIVE_END_DATE
  AND PAAM.EFFECTIVE_LATEST_CHANGE = 'Y'
  AND PAAM.PRIMARY_FLAG = 'Y'
  AND PAAM.ASSIGNMENT_TYPE = 'E'
  AND PAAM.ASSIGNMENT_STATUS_TYPE = 'ACTIVE'
  AND PPNF.NAME_TYPE = 'GLOBAL' --AND PAAM.ASSIGNMENT_NUMBER IN ('004160394')

  AND PAPF.PERSON_NUMBER IN (1049714)
ORDER BY 1
       , 2