SELECT Contrato.ASSIGNMENT_ID,
       Contrato.ASSIGNMENT_TYPE,
       Contrato.PRIMARY_FLAG,
       Contrato.EMPLOYEE_CATEGORY,
       Contrato.ASSIGNMENT_STATUS_TYPE,
       Contrato.ASSIGNMENT_NUMBER,
       DadosPessoais.PERSON_NUMBER,
       Name.FIRST_NAME,
       Name.MIDDLE_NAMES,
       Name.LAST_NAME,
       Name.FULL_NAME,
       Usuario.USER_GUID,
       Usuario.ACTIVE_FLAG,
       Usuario.USERNAME,
       Usuario.SUSPENDED
FROM PER_ALL_ASSIGNMENTS_M Contrato
INNER JOIN PER_ALL_PEOPLE_F DadosPessoais ON DadosPessoais.PERSON_ID = Contrato.PERSON_ID
AND TRUNC(SYSDATE) BETWEEN DadosPessoais.EFFECTIVE_START_DATE AND DadosPessoais.EFFECTIVE_END_DATE
INNER JOIN PER_PERSON_NAMES_F Name ON Name.PERSON_ID = Contrato.PERSON_ID
AND Name.NAME_TYPE = 'GLOBAL'
AND Name.CHAR_SET_CONTEXT = 'PTB'
INNER JOIN PER_PERSONS Pessoa ON Pessoa.PERSON_ID = Contrato.PERSON_ID
LEFT JOIN PER_USERS Usuario ON Usuario.USER_GUID = Pessoa.USER_GUID
WHERE Contrato.PRIMARY_FLAG = 'Y'
  AND Contrato.ASSIGNMENT_STATUS_TYPE='ACTIVE'
  AND TRUNC(SYSDATE) BETWEEN Contrato.EFFECTIVE_START_DATE AND Contrato.EFFECTIVE_END_DATE