SELECT
  AllAssignment.ASSIGNMENT_NUMBER,
  PersonNames.FIRST_NAME,
  PersonNames.LAST_NAME,
  AbsenceRecords.PER_ABSENCE_ENTRY_ID,
  AbsenceRecords.ABSENCE_TYPE_ID,
  AbsenceType.BASE_NAME,
  AbsenceType.MIN_DURATION,
  AbsenceType.MAX_DURATION,
  AbsenceType.STATUS,
  AbsenceType.ATTRIBUTE1,
  AbsenceType.ATTRIBUTE2,
  AbsenceRecords.ASSIGNMENT_ID,
  AbsenceRecords.LEGAL_ENTITY_ID,
  AbsenceRecords.PERSON_ID,
  TO_CHAR (AbsenceRecords.START_DATE, 'RRRR/MM/DD') START_DATE,
  TO_CHAR (AbsenceRecords.END_DATE, 'RRRR/MM/DD') END_DATE,
  IntegrationKeyMap.SOURCE_SYSTEM_ID,
  IntegrationKeyMap.SOURCE_SYSTEM_OWNER
FROM
  ANC_PER_ABS_ENTRIES AbsenceRecords
  LEFT JOIN ANC_ABSENCE_TYPES_F AbsenceType ON AbsenceType.ABSENCE_TYPE_ID = AbsenceRecords.ABSENCE_TYPE_ID
  AND SYSDATE BETWEEN AbsenceType.EFFECTIVE_START_DATE AND AbsenceType.EFFECTIVE_END_DATE
  LEFT JOIN HRC_INTEGRATION_KEY_MAP IntegrationKeyMap ON IntegrationKeyMap.SURROGATE_ID = AbsenceRecords.PER_ABSENCE_ENTRY_ID
  LEFT JOIN PER_ALL_ASSIGNMENTS_M AllAssignment ON AllAssignment.ASSIGNMENT_ID = AbsenceRecords.ASSIGNMENT_ID
  AND SYSDATE BETWEEN AllAssignment.EFFECTIVE_START_DATE AND AllAssignment.EFFECTIVE_END_DATE
  LEFT JOIN PER_PERSON_NAMES_F PersonNames ON PersonNames.PERSON_ID = AllAssignment.PERSON_ID
  AND PersonNames.NAME_TYPE = 'GLOBAL'
  AND SYSDATE BETWEEN PersonNames.EFFECTIVE_START_DATE AND PersonNames.EFFECTIVE_END_DATE
WHERE
  1 = 1
  AND AbsenceType.ATTRIBUTE1 = 7
  AND (TRUNC(AbsenceRecords.START_DATE) BETWEEN TO_DATE('2025-09-01', 'RRRR-MM-DD') AND TO_DATE('2025-09-30', 'RRRR-MM-DD')
  OR (TRUNC(AbsenceRecords.END_DATE) BETWEEN TO_DATE('2025-09-01', 'RRRR-MM-DD') AND TO_DATE('2025-09-30', 'RRRR-MM-DD') OR AbsenceRecords.END_DATE = '4712-12-31'))
ORDER BY
  AllAssignment.ASSIGNMENT_NUMBER,
  AbsenceRecords.START_DATE
  -- SELECT * FROM PER_ALL_PEOPLE_F WHERE PERSON_ID=300000055562896
  --300000055562896