SELECT
  LOCATION_DETAILS_ID,
  LOCATION_ID,
  MAIN_ADDRESS_ID,
  SHIP_TO_LOCATION_ID,
  INTERNAL_LOCATION_CODE,
  LOCATION_NAME,
  DESCRIPTION,
  ACTION_OCCURRENCE_ID
FROM
  hr_locations_all
WHERE
  ACTIVE_STATUS = 'A'
  AND TRUNC(SYSDATE) BETWEEN EFFECTIVE_START_DATE
  AND EFFECTIVE_END_DATE
  AND INTERNAL_LOCATION_CODE LIKE 'GM%'