--SQL Query to retrieve User Roles – Fusion Applications

SELECT PU.USERNAME
     , PRDT.ROLE_ID
     , PRDT.ROLE_NAME
     , PRD.ROLE_COMMON_NAME
     , PU.ACTIVE_FLAG
FROM PER_USER_ROLES PUR
INNER JOIN PER_USERS PU ON PU.USER_ID = PUR.USER_ID
AND PU.ACTIVE_FLAG = 'Y'
INNER JOIN PER_ROLES_DN_TL PRDT ON PRDT.ROLE_ID = PUR.ROLE_ID
INNER JOIN PER_ROLES_DN PRD ON PRDT.ROLE_ID = PRD.ROLE_ID
AND PRDT.LANGUAGE = USERENV ('LANG')
WHERE PU.USERNAME = NVL(:P_USERNAME, PU.USERNAME)
ORDER BY PU.USERNAME
       , PRDT.ROLE_NAME