SELECT PF.PERSON_NUMBER
     , A.ASSIGNMENT_NUMBER
     , PN.FULL_NAME
     , AC_TL.ACTION_NAME
     , RTL.ACTION_REASON
     , ST.USER_STATUS
     , TP.SYSTEM_PERSON_TYPE
     , PL.USER_PERSON_TYPE
     , NI.NATIONAL_IDENTIFIER_NUMBER AS CPF
     , CASE
           WHEN A.ASSIGNMENT_TYPE = UPPER('p') THEN TO_CHAR (A.PROJECTED_START_DATE
                                                           , 'DD/MM/YYYY')
           ELSE TO_CHAR (PP.DATE_START
                       , 'DD/MM/YYYY')
       END AS HIRE_DATE
     , TO_CHAR (A.EFFECTIVE_START_DATE
              , 'DD/MM/YYYY') AS START_DATE
             , TO_CHAR (A.EFFECTIVE_END_DATE
                      , 'DD/MM/YYYY') AS END_DATE
                     , RIF.ORG_INFORMATION1 AS ESTABLISHMENT_CODE
                     , EST.NAME AS ESTABLISHMENT_NAME
                     , LEMP.NAME AS EMPLOYER_NAME
                     , DEPT.INTERNAL_ADDRESS_LINE AS ADDRESS_LINE
                     , DEPT.NAME AS DEPARTAMENT_NAME
                     , JOB.JOB_CODE
                     , JTL.NAME AS JOB_NAME
                     , SDC.INTERNAL_ADDRESS_LINE AS UNION_CODE
                     , SDC.NAME AS UNION_NAME
                     , S.SALARY_AMOUNT
                     , POS.POSITION_CODE
                     , POS2.NAME AS POSITION_NAME
                     , FLV.FLEX_VALUE AS COST_CENTER
FROM PER_ALL_ASSIGNMENTS_M A
LEFT JOIN PER_PERIODS_OF_SERVICE PP ON PP.PERIOD_OF_SERVICE_ID = A.PERIOD_OF_SERVICE_ID
LEFT JOIN PER_PERIODS_OF_SERVICE PT ON PT.PERIOD_OF_SERVICE_ID = A.PERIOD_OF_SERVICE_ID
AND PT.ATTRIBUTE_CATEGORY = 'LACLS_BR_HCM_INFO_TERM'
LEFT JOIN FND_LOOKUP_VALUES_TL PTM ON PTM.LOOKUP_CODE = PT.ATTRIBUTE2
AND PTM.LOOKUP_TYPE = 'LACLS_BR_HCM_REA_PAY_TERM'
AND PTM.LANGUAGE = SYS_CONTEXT ('USERENV', 'LANG')
LEFT JOIN PER_PERIODS_OF_SERVICE PA ON PA.PERIOD_OF_SERVICE_ID = A.PERIOD_OF_SERVICE_ID
AND PA.ATTRIBUTE_CATEGORY = 'LACLS_BR_HCM_WORK_REL'
LEFT JOIN PER_PERSON_NAMES_F PN ON PN.PERSON_ID = A.PERSON_ID
AND PN.NAME_TYPE = 'BR'
AND TRUNC (NVL (TO_DATE (:P_DATA_REFERENCIA
                       , 'YYYY-MM-DD'), SYSDATE)) BETWEEN PN.EFFECTIVE_START_DATE AND PN.EFFECTIVE_END_DATE
LEFT JOIN PER_ALL_PEOPLE_F PF ON PF.PERSON_ID = A.PERSON_ID
AND TRUNC (NVL (TO_DATE (:P_DATA_REFERENCIA
                       , 'YYYY-MM-DD'), SYSDATE)) BETWEEN PF.EFFECTIVE_START_DATE AND PF.EFFECTIVE_END_DATE
LEFT JOIN PER_PERSON_TYPE_USAGES_M TP ON TP.PERSON_ID = A.PERSON_ID
AND TP.SYSTEM_PERSON_TYPE IN ('CWK'
                            , 'EMP'
                            , 'NONW')
AND TO_CHAR (TP.EFFECTIVE_END_DATE
           , 'DD/MM/YYYY') = '31/12/4712'
LEFT JOIN PER_PERSON_TYPES_TL PL ON PL.PERSON_TYPE_ID = TP.PERSON_TYPE_ID
AND PL.LANGUAGE = SYS_CONTEXT ('USERENV', 'LANG')
LEFT JOIN PER_ASSIGNMENT_STATUS_TYPES_TL ST ON ST.ASSIGNMENT_STATUS_TYPE_ID = A.ASSIGNMENT_STATUS_TYPE_ID
AND ST.LANGUAGE = SYS_CONTEXT ('USERENV', 'LANG')
LEFT JOIN PER_NATIONAL_IDENTIFIERS NI ON NI.PERSON_ID = PF.PERSON_ID
AND NI.NATIONAL_IDENTIFIER_TYPE = 'CPF'
LEFT JOIN HR_ORGANIZATION_V DEPT ON DEPT.ORGANIZATION_ID = A.ORGANIZATION_ID
AND DEPT.CLASSIFICATION_CODE = 'DEPARTMENT'
AND DEPT.STATUS = 'A'
AND TO_CHAR (DEPT.EFFECTIVE_END_DATE
           , 'DD/MM/YYYY') = '31/12/4712'
LEFT JOIN HR_ORGANIZATION_V LEMP ON LEMP.ORGANIZATION_ID = A.LEGAL_ENTITY_ID
AND LEMP.CLASSIFICATION_CODE = 'HCM_LEMP'
AND LEMP.STATUS = 'A'
AND TO_CHAR (LEMP.EFFECTIVE_END_DATE
           , 'DD/MM/YYYY') = '31/12/4712'
LEFT JOIN HR_ORGANIZATION_V BU ON BU.ORGANIZATION_ID = A.BUSINESS_UNIT_ID
AND BU.CLASSIFICATION_CODE = 'FUN_BUSINESS_UNIT'
AND BU.STATUS = 'A'
AND TRUNC (NVL (TO_DATE (:P_DATA_REFERENCIA
                       , 'YYYY-MM-DD'), SYSDATE)) BETWEEN BU.EFFECTIVE_START_DATE AND BU.EFFECTIVE_END_DATE
LEFT JOIN HR_ORGANIZATION_V SDC ON SDC.ORGANIZATION_ID = A.UNION_ID
AND SDC.CLASSIFICATION_CODE = 'ORA_PER_UNION'
AND SDC.STATUS = 'A'
AND TRUNC (NVL (TO_DATE (:P_DATA_REFERENCIA
                       , 'YYYY-MM-DD'), SYSDATE)) BETWEEN SDC.EFFECTIVE_START_DATE AND SDC.EFFECTIVE_END_DATE
LEFT JOIN PER_JOBS_F JOB ON (JOB.JOB_ID = A.JOB_ID
                             AND A.EFFECTIVE_END_DATE BETWEEN JOB.EFFECTIVE_START_DATE AND JOB.EFFECTIVE_END_DATE)
LEFT JOIN PER_JOBS_F_TL JTL ON (JTL.JOB_ID = JOB.JOB_ID
                                AND JTL.LANGUAGE = SYS_CONTEXT ('USERENV', 'LANG')
                                AND A.EFFECTIVE_END_DATE BETWEEN JTL.EFFECTIVE_START_DATE AND JTL.EFFECTIVE_END_DATE)
LEFT JOIN PER_ACTION_OCCURRENCES AO ON AO.ACTION_OCCURRENCE_ID = A.ACTION_OCCURRENCE_ID
LEFT JOIN PER_ACTIONS_B AC ON AC.ACTION_ID = AO.ACTION_ID
LEFT JOIN PER_ACTIONS_TL AC_TL ON AC_TL.ACTION_ID = AC.ACTION_ID
AND AC_TL.LANGUAGE = SYS_CONTEXT ('USERENV', 'LANG')
LEFT JOIN PER_ACTION_REASONS_B RCT ON RCT.ACTION_REASON_ID = AO.ACTION_REASON_ID
LEFT JOIN PER_ACTION_REASONS_TL RTL ON RTL.ACTION_REASON_ID = RCT.ACTION_REASON_ID
AND RTL.LANGUAGE = SYS_CONTEXT ('USERENV', 'LANG')
LEFT JOIN HR_ALL_POSITIONS_F POS ON POS.POSITION_ID = A.POSITION_ID
AND TO_CHAR (POS.EFFECTIVE_END_DATE
           , 'DD/MM/YYYY') = '31/12/4712'
LEFT JOIN FND_FLEX_VALUES FLV ON (FLV.FLEX_VALUE_ID = POS.COST_CENTER)
LEFT JOIN HR_ALL_POSITIONS_F_TL POS2 ON POS2.POSITION_ID = POS.POSITION_ID
AND POS2.LANGUAGE = SYS_CONTEXT ('USERENV', 'LANG')
AND POS.EFFECTIVE_END_DATE BETWEEN POS2.EFFECTIVE_START_DATE AND POS2.EFFECTIVE_END_DATE
INNER JOIN CMP_SALARY S ON S.ASSIGNMENT_ID = A.ASSIGNMENT_ID
AND TRUNC (NVL (TO_DATE (:P_DATA_REFERENCIA
                       , 'RRRR-MM-DD'), SYSDATE)) BETWEEN S.DATE_FROM AND S.DATE_TO
LEFT JOIN XLE_REGISTRATIONS_V RE ON (RE.REGISTRATION_NUMBER = A.ASS_ATTRIBUTE19
                                     AND RE.LEGAL_ENTITY_ID IS NULL
                                     AND A.EFFECTIVE_END_DATE BETWEEN NVL (RE.EFFECTIVE_FROM
                                                                         , TO_DATE ('1951-01-01'
                                                                                  , 'RRRR-MM-dd')) AND NVL (RE.EFFECTIVE_TO
                                                                                                          , TO_DATE ('4712-12-31'
                                                                                                                   , 'RRRR-mm-dd')))
LEFT JOIN HR_ORGANIZATION_V EST ON (EST.ESTABLISHMENT_ID = RE.ESTABLISHMENT_ID
                                    AND EST.STATUS = UPPER('a')
                                    AND EST.CLASSIFICATION_CODE = UPPER('hcm_reporting_establishment')
                                    AND A.EFFECTIVE_END_DATE BETWEEN EST.EFFECTIVE_START_DATE AND EST.EFFECTIVE_END_DATE)
LEFT JOIN HR_ORGANIZATION_INFORMATION_F RIF ON (RIF.ORG_INFORMATION_CONTEXT = UPPER('lacls_br_hcm_lru_code')
                                                AND RIF.ORGANIZATION_ID = EST.ORGANIZATION_ID
                                                AND A.EFFECTIVE_END_DATE BETWEEN RIF.EFFECTIVE_START_DATE AND RIF.EFFECTIVE_END_DATE)
WHERE 1 = 1
  AND TRUNC (NVL (TO_DATE (:P_DATA_REFERENCIA
                         , 'RRRR-MM-DD'), SYSDATE)) BETWEEN PF.EFFECTIVE_START_DATE AND PF.EFFECTIVE_END_DATE
  AND A.EFFECTIVE_LATEST_CHANGE = UPPER('Y')
  AND TO_CHAR (A.EFFECTIVE_END_DATE
             , 'DD/MM/YYYY') = '31/12/4712'
  AND A.ASSIGNMENT_TYPE IN ('E')
  AND ST.ASSIGNMENT_STATUS_TYPE_ID IN (1
                                     , 2)
  AND PF.PERSON_NUMBER LIKE '%' || NVL (:P_PERSON_NUMBER
                                      , PF.PERSON_NUMBER) || '%'
  AND PN.FULL_NAME LIKE '%' || NVL (:P_FULL_NAME
                                  , PN.FULL_NAME) || '%'
  AND JOB.JOB_CODE NOT LIKE '%1399%'
ORDER BY RIF.ORG_INFORMATION1 /*
ORDER BY A.EFFECTIVE_START_DATE
       , A.EFFECTIVE_SEQUENCE
       , TO_NUMBER (PF.PERSON_NUMBER)
       , PP.DATE_START */