SELECT PAPF.PERSON_ID
     , PAPF.PERSON_NUMBER
     , PU.USER_ID
     , PU.USERNAME
     , PU.USER_GUID
     , PU.START_DATE
     , PU.CREATED_BY
     , PU.CREATION_DATE
     , PU.LAST_UPDATED_BY
     , PU.LAST_UPDATE_DATE
     , PU.HR_TERMINATED
     , PU.SUSPENDED
     , PU.CREDENTIALS_EMAIL_SENT
     , PEA.EMAIL_ADDRESS
     , PPNF.FULL_NAME
FROM PER_ALL_PEOPLE_F PAPF
INNER JOIN PER_USERS PU ON PU.PERSON_ID = PAPF.PERSON_ID
LEFT JOIN PER_PERSON_NAMES_F PPNF ON PPNF.PERSON_ID = PAPF.PERSON_ID
AND PPNF.NAME_TYPE = 'GLOBAL'
AND TRUNC(SYSDATE) BETWEEN PPNF.EFFECTIVE_START_DATE AND PPNF.EFFECTIVE_END_DATE
LEFT JOIN PER_EMAIL_ADDRESSES PEA ON PEA.PERSON_ID = PAPF.PERSON_ID
WHERE 1 = 1
  AND TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
  AND PAPF.PERSON_NUMBER = NVL(:PU_PERSON_NUMBER, PAPF.PERSON_NUMBER)
  AND PU.USERNAME = NVL(:PU_USERNAME, PU.USERNAME)
  AND PPNF.FULL_NAME = NVL(:PU_FULL_NAME, PPNF.FULL_NAME)
ORDER BY PAPF.PERSON_NUMBER ASC
       , PU.USERNAME ASC NULLS FIRST