SELECT PJC.JOB_ID
     , PJC.EFFECTIVE_START_DATE AS START_DATE
     , PJC.EFFECTIVE_END_DATE END_DATE
     , PJC.JOB_CODE
     , PJC.NAME AS JOB_NAME
     , PJC.ACTIVE_STATUS
     , PJF.INFORMATION1 AS CBO
FROM PER_JOBS PJC
LEFT JOIN PER_JOB_LEG_F PJF ON PJF.JOB_ID = PJC.JOB_ID
AND PJC.EFFECTIVE_END_DATE BETWEEN PJF.EFFECTIVE_START_DATE AND PJF.EFFECTIVE_END_DATE
AND PJF.LEGISLATION_CODE = 'BR'
WHERE TRUNC(SYSDATE) BETWEEN PJC.EFFECTIVE_START_DATE AND PJC.EFFECTIVE_END_DATE
ORDER BY PJC.JOB_CODE