/* Query to fetch total number of processed hours that was raised by an employee*/
SELECT SUM(CASE WHEN A.UOM = 'HR' THEN A.PROCESSED_HOURS ELSE NULL END) AS TOTAL_PROCESSED_HOURS,
       A.PERSON_NUMBER AS PERSON_NUMBER
FROM
  ( SELECT PERSON_ASG_TABLE.PERSON_NUMBER PERSON_NUMBER,
           OTL_TABLE.UNIT_OF_MEASURE UOM,
           OTL_TABLE.MEASURE PROCESSED_HOURS,
           ASG_TABLE.ASSIGNMENT_ID ASSIGNMENT_ID,
           ASG_TABLE.EFFECTIVE_START_DATE ASSIGNMENT_EFFECTIVE_START_DATE,
           ASG_TABLE.EFFECTIVE_END_DATE ASSIGNMENT_EFFECTIVE_END_DATE,
           ASG_TABLE.EFFECTIVE_LATEST_CHANGE,
           ASG_TABLE.EFFECTIVE_SEQUENCE,
           OTL_TABLE.ORIG_TM_REC_ID,
           OTL_TABLE.TM_REC_ID,
           OTL_TABLE.TM_REC_VERSION,
           PERSON_ASG_TABLE.PAPF_PERSON_ID,
           PERSON_ASG_TABLE.PAPF_EFFECTIVE_START_DATE,
           PERSON_ASG_TABLE.PAPF_EFFECTIVE_END_DATE
   FROM
     ( SELECT HTRG1.GRP_TYPE_ID TC_GRP_TYPE_ID,
              HTRG1.DELETE_FLAG DELETE_FLAG,
              HTRG1.LATEST_VERSION LATEST_VERSION,
              HTRG.DELETE_FLAG DELETE_FLAG,
              HTRG.LATEST_VERSION LATEST_VERSION,
              HTR.TM_REC_ID TM_REC_ID,
              HTR.TM_REC_VERSION TM_REC_VERSION,
              HTR.ORIG_TM_REC_ID ORIG_TM_REC_ID,
              HTR.UNIT_OF_MEASURE UNIT_OF_MEASURE,
              HTR.DELETE_FLAG DELETE_FLAG,
              HTR.SUBRESOURCE_ID SUBRESOURCE_ID,
              HTR.LATEST_VERSION,
              HTR.MEASURE MEASURE
      FROM HWM_TM_REC HTR,
           HWM_TM_REC_GRP_USAGES HTRGU,
           HWM_TM_REC_GRP HTRG,
           HWM_TM_REC_GRP HTRG1
      WHERE (HTRGU.TM_REC_GRP_ID = HTRG.TM_REC_GRP_ID
             AND HTRGU.TM_REC_GRP_VERSION = HTRG.TM_REC_GRP_VERSION
             AND HTRG.PARENT_TM_REC_GRP_ID = HTRG1.TM_REC_GRP_ID
             AND HTRG.PARENT_TM_REC_GRP_VERSION = HTRG1.TM_REC_GRP_VERSION
             AND HTR.TM_REC_ID = HTRGU.TM_REC_ID
             AND HTR.TM_REC_VERSION = HTRGU.TM_REC_VERSION)
        AND ( HTRG1.GRP_TYPE_ID = 200
             AND HTRG1.DELETE_FLAG IS NULL
             AND HTRG1.LATEST_VERSION = 'Y'
             AND HTRG.DELETE_FLAG IS NULL
             AND HTRG.LATEST_VERSION = 'Y'
             AND HTR.DELETE_FLAG IS NULL
             AND HTR.LATEST_VERSION = 'Y'
             AND UPPER(HTR.UNIT_OF_MEASURE) = UPPER('HR')
             AND ((1 = 1))) ) OTL_TABLE,
     ( SELECT PAAM.ASSIGNMENT_ID,
              PAAM.EFFECTIVE_START_DATE,
              PAAM.EFFECTIVE_END_DATE,
              PAAM.EFFECTIVE_LATEST_CHANGE,
              PAAM.EFFECTIVE_SEQUENCE,
              PAAM.PERSON_ID
      FROM PER_ALL_ASSIGNMENTS_M PAAM
      WHERE (TRUNC(SYSDATE) BETWEEN TRUNC(PAAM.EFFECTIVE_START_DATE) AND TRUNC(PAAM.EFFECTIVE_END_DATE)) ) ASG_TABLE,
     ( SELECT PP.PERSON_ID PP_PERSON_ID,
              PAPF.PERSON_ID PAPF_PERSON_ID,
              PAPF.EFFECTIVE_START_DATE PAPF_EFFECTIVE_START_DATE,
              PAPF.EFFECTIVE_END_DATE PAPF_EFFECTIVE_END_DATE,
              PAPF.PERSON_NUMBER,
              PAAM.ASSIGNMENT_ID PAAM_ASSIGNMENT_ID,
              PAAM.PERSON_ID PAAM_PERSON_ID
      FROM PER_PERSONS PP,
           PER_ALL_PEOPLE_F PAPF,
           PER_ALL_ASSIGNMENTS_M PAAM
      WHERE (PP.PERSON_ID = PAPF.PERSON_ID
             AND PP.PERSON_ID = PAAM.PERSON_ID
             AND (TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE)
             AND (TRUNC(SYSDATE) BETWEEN PAAM.EFFECTIVE_START_DATE AND PAAM.EFFECTIVE_END_DATE))
        AND (PAAM.EFFECTIVE_LATEST_CHANGE = 'Y'
             AND PAAM.ASSIGNMENT_TYPE = 'E' ) ) PERSON_ASG_TABLE
   WHERE OTL_TABLE.SUBRESOURCE_ID = ASG_TABLE.ASSIGNMENT_ID
     AND ASG_TABLE.PERSON_ID = PERSON_ASG_TABLE.PAAM_PERSON_ID(+)
     AND ASG_TABLE.ASSIGNMENT_ID = PERSON_ASG_TABLE.PAAM_ASSIGNMENT_ID(+)) A
GROUP BY A.PERSON_NUMBER