SELECT DISTINCT ALLPEOPLE.PERSON_NUMBER
              ,  ALLASSIGNMENTS.PERSON_ID
              ,  ALLASSIGNMENTS.ASSIGNMENT_ID
              ,  ABSENCEENTRIES.PER_ABSENCE_ENTRY_ID
              ,  ABSENCETYPES.ABSENCE_TYPE_ID
              ,  ABSENCETYPES.NAME ABSENCE_TYPE
              ,  TO_CHAR(ABSENCEENTRIES.START_DATE, 'DD/MM/RRRR') START_DATE
              ,  TO_CHAR(NVL(ABSENCEENTRIES.END_DATE, '4712-12-31'), 'DD/MM/RRRR') END_DATE
              ,  ABSENCEENTRIES.DURATION
              ,  ALLASSIGNMENTS.ASSIGNMENT_NUMBER
              ,  ALLASSIGNMENTS.ASSIGNMENT_TYPE
              ,  ALLASSIGNMENTS.EMPLOYEE_CATEGORY
              ,  ALLASSIGNMENTS.ASSIGNMENT_STATUS_TYPE
              ,  SUBSTR(ALLASSIGNMENTS.ASSIGNMENT_NUMBER, 1, 3) EMPLOYER
              ,  SUBSTR(ALLASSIGNMENTS.ASSIGNMENT_NUMBER, 4, 50) EMPLOYEE
              ,  TO_CHAR(ALLASSIGNMENTS.EFFECTIVE_START_DATE, 'DD/MM/RRRR') ASSIGNMENT_EFFECTIVE_START_DATE
              ,  TO_CHAR(ALLASSIGNMENTS.EFFECTIVE_END_DATE, 'DD/MM/RRRR') ASSIGNMENT_EFFECTIVE_END_DATE
FROM ANC_PER_ABS_ENTRIES ABSENCEENTRIES
INNER JOIN PER_PERIODS_OF_SERVICE PERIODSOFSERVICE ON PERIODSOFSERVICE.PERIOD_OF_SERVICE_ID = ABSENCEENTRIES.PERIOD_OF_SERVICE_ID
INNER JOIN PER_ALL_PEOPLE_F ALLPEOPLE ON ALLPEOPLE.PERSON_ID = PERIODSOFSERVICE.PERSON_ID
AND TRUNC(SYSDATE) BETWEEN ALLPEOPLE.EFFECTIVE_START_DATE AND ALLPEOPLE.EFFECTIVE_END_DATE
INNER JOIN ANC_ABSENCE_TYPES_VL ABSENCETYPES ON ABSENCETYPES.ABSENCE_TYPE_ID = ABSENCEENTRIES.ABSENCE_TYPE_ID
AND TRUNC(SYSDATE) BETWEEN ABSENCETYPES.EFFECTIVE_START_DATE AND ABSENCETYPES.EFFECTIVE_END_DATE
INNER JOIN PER_ALL_ASSIGNMENTS_M ALLASSIGNMENTS ON ALLASSIGNMENTS.PERSON_ID = PERIODSOFSERVICE.PERSON_ID
AND ALLASSIGNMENTS.PERIOD_OF_SERVICE_ID = PERIODSOFSERVICE.PERIOD_OF_SERVICE_ID
AND ALLASSIGNMENTS.ASSIGNMENT_TYPE = 'E'
WHERE 1 = 1 --AND NVL(absenceentries.end_date, TO_DATE('4712-12-31', 'YYYY-MM-DD')) > allassignments.effective_end_date --Data fim maior que a effective_end_date do assignment
  AND ALLASSIGNMENTS.ASSIGNMENT_NUMBER = '0041949'