SELECT 
    RE.REGISTRATION_NUMBER, 
    RE.ESTABLISHMENT_ID, 
    RE.ESTABLISHMENT_NAME, 
    RIF.ORG_INFORMATION1
FROM 
    XLE_REGISTRATIONS_V RE 
LEFT JOIN 
    HR_ORGANIZATION_V EST ON EST.ESTABLISHMENT_ID = RE.ESTABLISHMENT_ID 
    AND EST.STATUS = UPPER('A')
    AND EST.CLASSIFICATION_CODE = UPPER('hcm_reporting_establishment')
    AND SYSDATE BETWEEN EST.EFFECTIVE_START_DATE AND EST.EFFECTIVE_END_DATE 
LEFT JOIN 
    HR_ORGANIZATION_INFORMATION_F RIF ON RIF.ORG_INFORMATION_CONTEXT = UPPER('lacls_br_hcm_lru_code')
    AND RIF.ORGANIZATION_ID = EST.ORGANIZATION_ID 
    AND SYSDATE BETWEEN RIF.EFFECTIVE_START_DATE AND RIF.EFFECTIVE_END_DATE 
WHERE 
    RE.LEGAL_ENTITY_ID IS NULL 
    AND SYSDATE BETWEEN 
        NVL(RE.EFFECTIVE_FROM, TO_DATE('1951-01-01', 'yyyy-mm-dd')) 
        AND NVL(RE.EFFECTIVE_TO, TO_DATE('4712-12-31', 'yyyy-mm-dd'))
        AND RIF.ORG_INFORMATION1 = 122