SELECT DISTINCT T.OBJECT_NAME AS TABLE_NAME, C.COLUMN_NAME
FROM ALL_OBJECTS T
LEFT JOIN ALL_TAB_COLUMNS C ON T.OBJECT_NAME = C.TABLE_NAME
AND T.OWNER = C.OWNER
WHERE T.OWNER = 'FUSION_SETUP'
  AND T.OBJECT_TYPE IN ('TABLE', 'VIEW')
  --AND T.OBJECT_NAME LIKE 'per_all_people_f%'
ORDER BY T.OBJECT_NAME, C.COLUMN_NAME