WITH EMPREGADOS AS (
    SELECT NI.NATIONAL_IDENTIFIER_NUMBER AS CPF,
           PF.PERSON_NUMBER AS NUMERO_DA_PESSOA,
           A.ASSIGNMENT_NUMBER AS ASSIGNMENT_NUMBER,
           SUBSTR(A.ASSIGNMENT_NUMBER, 1, 3) AS EMPRESA,
           SUBSTR(A.ASSIGNMENT_NUMBER, 4) AS MATRICULA,
           PN.FULL_NAME AS COLABORADOR,
           LEMP.NAME AS EMPRESA_LEGAL,
           BU.NAME AS UNIDADE_NEGOCIO,
           AC_TL.ACTION_NAME AS ACAO,
           RTL.ACTION_REASON AS MOTIVO,
           STTL.USER_STATUS AS STATUS,
           TP.SYSTEM_PERSON_TYPE AS TIPO_PESSOA,
           PL.USER_PERSON_TYPE AS TIPO_USUARIO,
           CASE
               WHEN SERD.ENTRY_DATE IS NULL THEN A.EFFECTIVE_START_DATE
               ELSE SERD.ENTRY_DATE
           END AS DT_ADMISSAO,
           TO_CHAR(A.EFFECTIVE_START_DATE, 'DD/MM/YYYY') AS DATA_MOVIMENTACAO,
           TO_CHAR(A.EFFECTIVE_END_DATE, 'DD/MM/YYYY') AS DATA_FINAL,
           RIF.ORG_INFORMATION1 AS CODIGO_FILIAL,
           EST.NAME AS FILIAL,
           TO_CHAR(PP.ACTUAL_TERMINATION_DATE, 'DD/MM/YYYY') AS DATA_DESLIGAMENTO,
           PTM.MEANING AS MOT_REM_DESLIG,
           DEPT.INTERNAL_ADDRESS_LINE AS COD_SETOR,
           DEPT.NAME AS DEPARTAMENTO,
           JOB.JOB_CODE AS COD_CARGO,
           JTL.NAME AS CARGO,
           SDC.INTERNAL_ADDRESS_LINE AS COD_SINDICATO,
           SDC.NAME AS SINDICATO,
           S.SALARY_AMOUNT AS SALARIO,
           POS.POSITION_CODE AS CODIGO_POSICAO,
           POS2.NAME AS NOME_POSICAO,
           DEF.DISABILITY_ID AS COD_DEF,
           TO_CHAR(A.CREATION_DATE - INTERVAL '3' HOUR, 'DD/MM/YYYY HH24:MI:SS') AS DATA_CRIACAO2
    FROM PER_ALL_ASSIGNMENTS_M A
    LEFT JOIN PER_PERIODS_OF_SERVICE PP ON PP.PERIOD_OF_SERVICE_ID = A.PERIOD_OF_SERVICE_ID
    LEFT JOIN PER_PERIODS_OF_SERVICE PT ON PT.PERIOD_OF_SERVICE_ID = A.PERIOD_OF_SERVICE_ID
        AND PT.ATTRIBUTE_CATEGORY = 'LACLS_BR_HCM_INFO_TERM'
    LEFT JOIN FND_LOOKUP_VALUES_TL PTM ON PTM.LOOKUP_CODE = PT.ATTRIBUTE2
        AND PTM.LOOKUP_TYPE = 'LACLS_BR_HCM_REA_PAY_TERM'
        AND PTM.LANGUAGE = USERENV('LANG')
    LEFT JOIN PER_PERIODS_OF_SERVICE PA ON PA.PERIOD_OF_SERVICE_ID = A.PERIOD_OF_SERVICE_ID
        AND PA.ATTRIBUTE_CATEGORY = 'LACLS_BR_HCM_WORK_REL'
    LEFT JOIN PER_PERSON_NAMES_F PN ON PN.PERSON_ID = A.PERSON_ID
        AND PN.NAME_TYPE = 'BR'
        AND TO_CHAR(PN.EFFECTIVE_END_DATE, 'DD/MM/YYYY') = '31/12/4712'
    LEFT JOIN PER_ALL_PEOPLE_F PF ON PF.PERSON_ID = A.PERSON_ID
        AND TO_CHAR(PF.EFFECTIVE_END_DATE, 'DD/MM/YYYY') = '31/12/4712'
    LEFT JOIN PER_PERSON_TYPE_USAGES_M TP ON TP.PERSON_ID = A.PERSON_ID
        AND TP.SYSTEM_PERSON_TYPE IN ('CWK', 'EMP', 'NONW')
        AND TO_CHAR(TP.EFFECTIVE_END_DATE, 'DD/MM/YYYY') = '31/12/4712'
    LEFT JOIN PER_PERSON_TYPES_TL PL ON PL.PERSON_TYPE_ID = TP.PERSON_TYPE_ID
        AND PL.LANGUAGE = USERENV('LANG')
    LEFT JOIN PER_ASSIGNMENT_STATUS_TYPES_TL STTL ON STTL.ASSIGNMENT_STATUS_TYPE_ID = A.ASSIGNMENT_STATUS_TYPE_ID
        AND STTL.LANGUAGE = USERENV('LANG')
    LEFT JOIN PER_NATIONAL_IDENTIFIERS NI ON NI.PERSON_ID = PF.PERSON_ID
        AND NI.NATIONAL_IDENTIFIER_TYPE = 'CPF'
    LEFT JOIN HR_ORGANIZATION_V DEPT ON DEPT.ORGANIZATION_ID = A.ORGANIZATION_ID
        AND DEPT.CLASSIFICATION_CODE = 'DEPARTMENT'
        AND DEPT.STATUS = 'A'
        AND TO_CHAR(DEPT.EFFECTIVE_END_DATE, 'DD/MM/YYYY') = '31/12/4712'
    LEFT JOIN HR_ORGANIZATION_V LEMP ON LEMP.ORGANIZATION_ID = A.LEGAL_ENTITY_ID
        AND LEMP.CLASSIFICATION_CODE = 'HCM_LEMP'
        AND LEMP.STATUS = 'A'
        AND TO_CHAR(LEMP.EFFECTIVE_END_DATE, 'DD/MM/YYYY') = '31/12/4712'
    LEFT JOIN HR_ORGANIZATION_V BU ON BU.ORGANIZATION_ID = A.BUSINESS_UNIT_ID
        AND BU.CLASSIFICATION_CODE = 'FUN_BUSINESS_UNIT'
        AND BU.STATUS = 'A'
        AND TO_CHAR(BU.EFFECTIVE_END_DATE, 'DD/MM/YYYY') = '31/12/4712'
    LEFT JOIN HR_ORGANIZATION_V SDC ON SDC.ORGANIZATION_ID = A.UNION_ID
        AND SDC.CLASSIFICATION_CODE = 'ORA_PER_UNION'
        AND SDC.STATUS = 'A'
        AND TO_CHAR(SDC.EFFECTIVE_END_DATE, 'DD/MM/YYYY') = '31/12/4712'
    LEFT JOIN PER_JOBS_F JOB ON JOB.JOB_ID = A.JOB_ID
        AND TO_CHAR(JOB.EFFECTIVE_END_DATE, 'DD/MM/YYYY') = '31/12/4712'
    LEFT JOIN PER_JOBS_F_TL JTL ON JTL.JOB_ID = JOB.JOB_ID
        AND JTL.LANGUAGE = USERENV('LANG')
        AND TO_CHAR(JTL.EFFECTIVE_END_DATE, 'DD/MM/YYYY') = '31/12/4712'
    LEFT JOIN PER_ACTION_OCCURRENCES AO ON AO.ACTION_OCCURRENCE_ID = A.ACTION_OCCURRENCE_ID
    LEFT JOIN PER_ACTIONS_B AC ON AC.ACTION_ID = AO.ACTION_ID
    LEFT JOIN PER_ACTIONS_TL AC_TL ON AC_TL.ACTION_ID = AC.ACTION_ID
        AND AC_TL.LANGUAGE = USERENV('LANG')
    LEFT JOIN PER_ACTION_REASONS_B RCT ON RCT.ACTION_REASON_ID = AO.ACTION_REASON_ID
    LEFT JOIN PER_ACTION_REASONS_TL RTL ON RTL.ACTION_REASON_ID = RCT.ACTION_REASON_ID
        AND RTL.LANGUAGE = USERENV('LANG')
    LEFT JOIN FND_LOOKUP_VALUES_TL LKP_FRE ON LKP_FRE.LOOKUP_CODE = A.FREQUENCY
        AND LKP_FRE.LOOKUP_TYPE = 'FREQUENCY'
        AND LKP_FRE.LANGUAGE = USERENV('LANG')
    LEFT JOIN FND_LOOKUP_VALUES_TL LKP_UNI ON LKP_UNI.LOOKUP_CODE = A.PROBATION_UNIT
        AND LKP_UNI.LOOKUP_TYPE = 'QUALIFYING_UNITS'
        AND LKP_UNI.LANGUAGE = USERENV('LANG')
    LEFT JOIN FND_LOOKUP_VALUES_TL LKP_UNII ON LKP_UNII.LOOKUP_CODE = A.NOTICE_PERIOD_UOM
        AND LKP_UNII.LOOKUP_TYPE = 'QUALIFYING_UNITS'
        AND LKP_UNII.LANGUAGE = USERENV('LANG')
    LEFT JOIN FND_LOOKUP_VALUES_TL EP_CTG ON EP_CTG.LOOKUP_CODE = A.ASS_ATTRIBUTE2
        AND EP_CTG.LOOKUP_TYPE = 'ORA_HRX_BR_WORKER_CATEGORY'
        AND EP_CTG.LANGUAGE = USERENV('LANG')
    LEFT JOIN FND_LOOKUP_VALUES_TL CO_CTG ON CO_CTG.LOOKUP_CODE = A.EMPLOYEE_CATEGORY
        AND CO_CTG.LOOKUP_TYPE = 'EMPLOYEE_CATG'
        AND CO_CTG.LANGUAGE = USERENV('LANG')
    LEFT JOIN FND_LOOKUP_VALUES_TL FPT ON FPT.LOOKUP_CODE = A.FULL_PART_TIME
        AND FPT.LOOKUP_TYPE = 'PART_FULL_TIME'
        AND FPT.LANGUAGE = USERENV('LANG')
    LEFT JOIN FND_LOOKUP_VALUES_TL HS ON HS.LOOKUP_CODE = A.HOURLY_SALARIED_CODE
        AND HS.LOOKUP_TYPE = 'HOURLY_SALARIED_CODE'
        AND HS.LANGUAGE = USERENV('LANG')
    LEFT JOIN FND_LOOKUP_VALUES_TL RT ON RT.LOOKUP_CODE = A.PERMANENT_TEMPORARY_FLAG
        AND RT.LOOKUP_TYPE = 'REGULAR_TEMPORARY'
        AND RT.LANGUAGE = USERENV('LANG')
    LEFT JOIN HR_ALL_POSITIONS_F POS ON POS.POSITION_ID = A.POSITION_ID
        AND TO_CHAR(POS.EFFECTIVE_END_DATE, 'DD/MM/YYYY') = '31/12/4712'
    LEFT JOIN HR_ALL_POSITIONS_F_TL POS2 ON POS2.POSITION_ID = POS.POSITION_ID
        AND TO_CHAR(POS2.EFFECTIVE_END_DATE, 'DD/MM/YYYY') = '31/12/4712'
        AND POS2.LANGUAGE = USERENV('LANG')
    LEFT JOIN PER_DISABILITIES_F DEF ON DEF.PERSON_ID = PF.PERSON_ID
        AND TO_CHAR(DEF.EFFECTIVE_END_DATE, 'DD/MM/YYYY') = '31/12/4712'
    LEFT JOIN CMP_SALARY S ON S.ASSIGNMENT_ID = A.ASSIGNMENT_ID
        AND TO_CHAR(S.DATE_TO, 'DD/MM/YYYY') = '31/12/4712'
    LEFT JOIN PER_SENIORITY_DATES_F SERD ON SERD.PERSON_ID = PF.PERSON_ID
        AND SERD.LEVEL_CODE = 'ORA_P'
        AND SERD.SENIORITY_DATE_CODE IN ('LACLS_BR_HCM_SD_E', 'ORA_PER_MIGR_ESD_P')
        AND SERD.ENTRY_DATE = (
            SELECT MAX(SERDX.ENTRY_DATE)
            FROM PER_SENIORITY_DATES_F SERDX
            WHERE SERDX.PERSON_ID = PF.PERSON_ID
                AND SERDX.LEVEL_CODE = 'ORA_P'
            GROUP BY SERDX.PERSON_ID
        )
    LEFT JOIN XLE_REGISTRATIONS_V RE ON (RE.REGISTRATION_NUMBER = A.ASS_ATTRIBUTE19
        AND RE.LEGAL_ENTITY_ID IS NULL
        AND A.EFFECTIVE_END_DATE BETWEEN NVL(RE.EFFECTIVE_FROM, TO_DATE('1951-01-01', 'yyyy-mm-dd')) AND NVL(RE.EFFECTIVE_TO, TO_DATE('4712-12-31', 'yyyy-mm-dd')))
    LEFT JOIN HR_ORGANIZATION_V EST ON (EST.ESTABLISHMENT_ID = RE.ESTABLISHMENT_ID
        AND EST.STATUS = UPPER('A')
        AND EST.CLASSIFICATION_CODE = UPPER('hcm_reporting_establishment')
        AND A.EFFECTIVE_END_DATE BETWEEN EST.EFFECTIVE_START_DATE AND EST.EFFECTIVE_END_DATE)
    LEFT JOIN HR_ORGANIZATION_INFORMATION_F RIF ON (RIF.ORG_INFORMATION_CONTEXT = UPPER('lacls_br_hcm_lru_code')
        AND RIF.ORGANIZATION_ID = EST.ORGANIZATION_ID
        AND A.EFFECTIVE_END_DATE BETWEEN RIF.EFFECTIVE_START_DATE AND RIF.EFFECTIVE_END_DATE)
    WHERE 1 = 1
        AND TO_CHAR(A.EFFECTIVE_END_DATE, 'DD/MM/YYYY') = '31/12/4712'
        AND A.ASSIGNMENT_TYPE IN ('E')
        AND STTL.ASSIGNMENT_STATUS_TYPE_ID = 1 -- 'Ativo - Elegí­vel para Folha de Pagamento'
        -- AND A.ASSIGNMENT_NUMBER = '0041949'
    ORDER BY A.EFFECTIVE_START_DATE,
             A.EFFECTIVE_SEQUENCE,
             TO_NUMBER(PF.PERSON_NUMBER),
             PP.DATE_START
)
SELECT DISTINCT *
FROM EMPREGADOS;