SELECT PERSON_ID
     ,  MANAGER_ID
     ,  PRIMARY_FLAG
FROM PER_ASSIGNMENT_SUPERVISORS_F
WHERE PERSON_ID IN
    (SELECT PERSON_ID
     FROM PER_PERSON_NAMES_F
     WHERE TRUNC(SYSDATE) BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
       AND NAME_TYPE = 'GLOBAL'
       AND FULL_NAME LIKE '%PEDRO HENRIQUE BONFANTI CAMPEOTTO%')
  AND TRUNC(SYSDATE) BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE